name: Code Quality

on:
  pull_request:
  push:
    branches: [ "main", "develop" ]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # importante pra diff

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: xml

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      # 🔍 Pega arquivos alterados
      - name: Get changed PHP files
        id: changed-files
        run: |
          FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep \.php$ || true)
          echo "files=$FILES" >> $GITHUB_OUTPUT

      # 🛠 PHP-CS-Fixer
      - name: Run PHP-CS-Fixer
        if: steps.changed-files.outputs.files != ''
        run: |
          echo "${{ steps.changed-files.outputs.files }}" | xargs vendor/bin/php-cs-fixer fix --dry-run --diff

      # 🔍 PHPCS
      - name: Run PHPCS
        if: steps.changed-files.outputs.files != ''
        run: |
          echo "${{ steps.changed-files.outputs.files }}" | xargs vendor/bin/phpcs
